server:
  port: 24000
batch:
  files:
    base-path: ../grades-batch
university:
  servlet:
    trace-id-header-name: X-Transaction-Id
  kafka:
    topics:
      audit: university.audit.events

spring:
  application:
    name: university-administration

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

    consumer:
      group-id: audit-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.university.administration.infrastructure.kafka.model.AuditEvent
        spring.json.use.type.headers: false

      listener:
        concurrency: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      idle-timeout: 300000
      max-lifetime: 840000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 20000
      initialization-fail-timeout: 0
      pool-name: HikariPool-1
logging:
  level:
    org.springframework.batch: DEBUG
